# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('link', models.URLField(default='', max_length=100, verbose_name='广告地址')),
                ('img', models.ImageField(upload_to='static/images/poster', verbose_name='图片')),
            ],
        ),
    ]
