# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': '广告位', 'verbose_name_plural': '广告位'},
        ),
        migrations.AddField(
            model_name='comment',
            name='views',
            field=models.IntegerField(default=0, verbose_name='评论的点击量'),
        ),
    ]
