# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='sex',
            field=models.CharField(default='', max_length=10, verbose_name='性别'),
        ),
    ]
